---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
    exclude_paths:
    - "!**.md"
checks:
  method-complexity:
    config:
      threshold: 10
exclude_paths:
- "*"
- "!lib/"
- "!diaspora.js"
